name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository != 'KDE/kdeconnect-android'

    steps:
      - name: Sync Fork
        uses: aormsby/Fork-Sync-With-Upstream-Repo@v3.4
        with:
          upstream_repo: https://github.com/KDE/kdeconnect-android.git
          target_sync_branch: master
          target_repo_token: ${{ secrets.PAT_TOKEN }}
          upstream_pull_bool: false
